### ISSUE TITLE
Add support for Swift

### ISSUE THREAD

**Issue by dhoepfl** [tomaz/appledoc#460]
Since Apple has revealed its new programming language "Swift", appledoc should support it as valid input. Swift is here and it will not go away any time soon.

I do understand that this is a major change to appledoc.

**Comment by atljeremy** [comment]
Is this still going to happen? This issue's been open for over 1.5 years now. I saw there is a "3.0-development" release but I tried that and it doesn't seem to be working for Swift. Any updates on this?

**Comment by tomaz** [comment]
I certainly hope so :) There's effort to develop 3.0 with a group of developers joining in. I prepared starter project and am overlooking the development but can't do much coding due to time constraints; so far the pace was on the slower side, but hope it'll pick up. You're all welcome to join and help make it happen though - check readme file / contact me and I'll add you to project ;)

**Comment by alokc83** [comment]
I would like to contribute to swift support. please add me to the swift dev. thanks

**Comment by Coeur** [comment]
You can make pull requests before being a collaborator. :)

**Comment by tomaz** [comment]
@alokc83 Sure, I'll add you to the project. You can start by reading style and collaborator guides on development branch to get familiar with workflow.

**Comment by tomaz** [comment]
@alokc83 Added you to github, please let me know your email so I can add you to Trello and Slack as well (can use the contact form on http://gentlebytes.com/contact or email me directly if you'd like to keep it private)

**Comment by kihab** [comment]
Any updates on the Swift Support :) or the appledoc 3.0 Version ?!
@tomaz

**Comment by tomaz** [comment]
So far very little progress was done...
