### ISSUE TITLE
HTML generation formatting gets messed up on mobile.

### ISSUE THREAD

**Issue by joemasilotti** [tomaz/appledoc#553]
There are a few overlapping elements when viewing generated HTML documentation on a mobile device. Please see the screenshots of [the same page](http://masilotti.com/xctest-documentation) on desktop and mobile.

**Desktop**
![XCTest Documentation - Desktop](http://i.imgur.com/gN9Lam2.png)

**Mobile**
![XCTest Documentation - Mobile](http://i.imgur.com/GYSUndv.jpg)

For reference, I am generating the docs [with this command](https://github.com/joemasilotti/XCTest-Documentation/blob/master/README.md#generation).

**Comment by TorreyBetts** [comment]
This issue is now resolved. Follow these steps to ensure the fix is applied.

 1. Delete the **~/.appledoc** folder
 2. Clone the appledoc repository: **git clone git://github.com/tomaz/appledoc.git**
 3. Add the template option for the installation command: **sudo sh install-appledoc.sh -t default**

**Comment by joemasilotti** [comment]
Awesome! Looks great, thanks @TorreyBetts. :+1: 

![img_0868](https://cloud.githubusercontent.com/assets/2092156/10663627/cd2fbaea-788a-11e5-9df9-bc226ad4ff8c.jpg)
