### ISSUE TITLE
GBDocSetInstallGenerator failed generating output, aborting!

### ISSUE THREAD

**Issue by kevinlishuai** [tomaz/appledoc#598]
I found this didn't work on Xcode 8

**Comment by ljysdfz** [comment]
Ditto..
Output sth weird underneath:

> Generation step 4/5 failed: GBDocSetInstallGenerator failed generating output, aborting!
> Documentation set was installed, but couldn't reload documentation within Xcode.
> Expected end of line but found identifier.

**Comment by brianramirez** [comment]
Found this same issue occurs with Xcode 8.1 and appledoc version 2.2.1 (build 1334) ... Any word on what causes this or a fix?

**Comment by nmaoTV** [comment]
same here...

**Comment by tomaz** [comment]
I don't think Xcode in its latest versions supports installing docsets the way it's implemented in appledoc

**Comment by Huang-Libo** [comment]
Same issue. how to use `appledoc` in `Xcode 8.x`? @tomaz

**Comment by tomaz** [comment]
Well, docset should still get installed to `~/Library/Developer/Shared/Documentation/DocSets`, it's just that since Xcode 8 it's no longer possible to tell Xcode to refresh using AppleScript - you basically need to relaunch it.

**Comment by Huang-Libo** [comment]
But I got a empty `docset` in `~/Library/Developer/Shared/Documentation/DocSets`

**Comment by tomaz** [comment]
That's different issue then - check console log from appledoc (optionally increase verbosity) to see what's going on

**Comment by mjswan** [comment]
Same issue using appledoc 2.2.1 (build 1334) and Ruby 2.4.2p198 on OS X 10.12.6, Xcode 9.1. Running appledoc with --verbose 6 doesn't give me useful information. I can actually live without the docset but what I'd really like is the html output, which also fails to be produced.

Here's the tail of the output:
VERBOSE | Generation step 4/4: Running GBDocSetInstallGenerator...
INFO | Installing DocSet...
VERBOSE | GBDocSetInstallGenerator is generating output...
VERBOSE | Installing DocSet to Xcode...
Generation step 4/4 failed: GBDocSetInstallGenerator failed generating output, aborting!
Documentation set was installed, but couldn't reload documentation within Xcode.
Expected end of line but found identifier.
INFO | Finished generating in 3654ms.

**Comment by Kmohamed** [comment]
@tomaz I still faced this issue on Xcode 9.x is there any work arounds ?

**Comment by tomaz** [comment]
Hard to say from what is written here. I suggest increasing verbosity level and check the logs, or even better - run appledoc sources from Xcode and debug into the issue to see why docset is empty. Could be any number of reasons ranging from disabled docset generation (via cmd line or settings file), to corrupted or invalid templates.

Either way, nothing changed in Xcode 9 as far as docset installation goes, and I don't expect anything will in future versions. So, you need to restart Xcode in order to make it refresh docsets. But appledoc should still be able to generate one - this is independent.

**Comment by Kmohamed** [comment]
Actually the docset created Also I increase the verbosity level but I can get a hint what is going wrong

Copying '/Users/khaledElMorabea/Documents/ios/MyApp-Docs/docset' to '/Users/khaledElMorabea/Library/Developer/Shared/Documentation/DocSets/com.MyApp.MyApp.docset'...
Removing '/Users/khaledElMorabea/Library/Developer/Shared/Documentation/DocSets/com.MyApp.MyApp.docset'...
Generation step 4/5: Running GBDocSetInstallGenerator...
Installing DocSet...
GBDocSetInstallGenerator is generating output...
Installing DocSet to Xcode...
Generation step 4/5 failed: GBDocSetInstallGenerator failed generating output, aborting!
Documentation set was installed, but couldn't reload documentation within Xcode.
Expected end of line but found identifier.
Finished generating in 1658ms.

**Comment by Kmohamed** [comment]
I tried to debug it but I got this error when trying to load documentation set

{
    NSAppleScriptErrorBriefMessage = "Expected end of line but found identifier.";
    NSAppleScriptErrorMessage = "Expected end of line but found identifier.";
    NSAppleScriptErrorNumber = "-2741";
    NSAppleScriptErrorRange = "NSRange: {31, 13}";
}

**Comment by tomaz** [comment]
This confirms it's the problem I outlined originally: installation of docset via AppleScript is no longer supported since Xcode 8+. And as said, I don't think this will come back. The only workaround at this point is to restart Xcode in order to force it to load updated docset. And if you need to get appledoc return 0, then exclude docset installation via cmd line.

**Comment by Kmohamed** [comment]
Thanks a lot. But how can I launch doset using cmd ?

**Comment by tomaz** [comment]
At the moment you need to restart Xcode in order to let it update. Perhaps there is another way to tell it to refresh docsets but I am not aware of it. Though on the other hand I also don't see much of a usecase in updating docset regularly - Xcode should still pick up documentation from sources without any additional setup from developer. So restarting when needed should not be that much of a hassle...

**Comment by Kmohamed** [comment]
The problem that i am using appledoc with CircleCI and I don’t think so that i fan restart Xcode

**Comment by tomaz** [comment]
Hmm, I'm not familiar with CircleCI, but based on experience with other CI apps (Travis for example) the underlying Xcode VM is started from scratch on every build. So installing docset doesn't have any effect basically. But you do want to prevent reporting failure, that's why I suggested to exclude docset installation phase from appledoc
